services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-1
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/
    healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 30s
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx-1
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    command: sh -c "dockerize -wait tcp://php:9000 -timeout 30s nginx -g 'daemon off;'"
    
    depends_on:
      php:
      condition: service_healthy

  db:
    image: mariadb:latest
    container_name: mysql-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "laravel_password"
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql